# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160715074857 on 2016-08-01 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyTrello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create date:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='created_by',
            field=models.CharField(default='r', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Due date:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='list_description',
            field=models.CharField(default='done', max_length=500),
            preserve_default=False,
        ),
    ]
