# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160715074857 on 2016-08-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyTrello', '0002_auto_20160801_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='create_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.CharField(max_length=100),
        ),
    ]
